add_newline = false
format = "$directory${custom.branch}$character"

[directory]
truncation_length = 2
truncate_to_repo = false

[git_branch]
format = "[$symbol$branch]($style) "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

# kill the noise
[aws]
disabled = true
[gcloud]
disabled = true
[azure]
disabled = true
[nodejs]
disabled = true
[package]
disabled = true
[git_status]
disabled = true
[cmd_duration]
disabled = true

[custom.branch]
command = "/Users/giladkestenberg/.config/starship/pr-branch.sh"
when = "git rev-parse --is-inside-work-tree"
format = "[$output]($style) "
style = "bold purple"
shell = ["bash", "--noprofile", "--norc"]
