set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'catppuccin/tmux'

set-option -sg escape-time 1
set-option -ga terminal-overrides ",*-256color*:Tc"
set-option -g default-terminal "tmux-256color"
bind r source-file ~/.tmux.conf \; display "Reloaded"

set-option -g history-limit 10000

# Prefix
set-option -g prefix C-Space
unbind C-b
bind C-Space send-prefix

# Spliting
bind | split-window -h
bind - split-window -v

# Resize
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Selecting
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind e select-layout tiled 
bind v select-layout even-vertical
bind V select-layout even-horizontal
bind Enter resize-pane -Z

bind -r ( switch-client -p
bind -r ) switch-client -n

bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

set-option -g base-index 1
set-window-option -g pane-base-index 1

# Status
set-option -g status on
set-option -g status-interval 5

# Vim / Tmux Pane Switching
bind -n C-h run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-h) || tmux select-pane -L"
bind -n C-j run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-j) || tmux select-pane -D"
bind -n C-k run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-k) || tmux select-pane -U"
bind -n C-l run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-l) || tmux select-pane -R"
bind -n C-\\ run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys 'C-\\') || tmux select-pane -l"

set -g @catppuccin_date_time "%Y-%m-%d %H:%M"
set -g @catppuccin_host "on"
set -g @catppuccin_left_separator "█"
set -g @catppuccin_right_separator "█"
set -g @catppuccin_flavour 'mocha'

run -b '~/.tmux/plugins/tpm/tpm'
